-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

CREATE OR REPLACE FUNCTION fib(int)
RETURNS INTEGER AS $$
BEGIN
  RETURN CASE
    WHEN $1 = 0 THEN 0
    WHEN $1 = 1 THEN 1
  ELSE
    fib($1 - 1) + fib($1 - 2)
  END;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fibSum(int)
RETURNS INTEGER AS $$
BEGIN
  IF $1 <= 0 THEN
    RETURN 0;
  ELSIF $1 = 1 THEN
    RETURN 1;
  ELSE
    RETURN fibSum(0, $1, 0, 1);
  END IF;
END;
$$ LANGUAGE plpgsql;

WITH RECURSIVE fibSum(soFar, n, lastFib, beforeLastFib) AS (
  SELECT CASE
    WHEN lastFib = 0 AND beforeLastFib IS NULL THEN 0
    WHEN lastFib = 1 AND beforeLastFib = 0 THEN 1
    ELSE fibSum(soFar + lastFib, n - 1, lastFib, beforeLastFib + lastFib)
  END
)
-- SELECT fibSum(10);
