-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

CREATE OR REPLACE FUNCTION fib(int)
RETURNS INTEGER AS $$
BEGIN
  RETURN CASE
    WHEN $1 = 0 THEN 0
    WHEN $1 = 1 THEN 1
  ELSE
    fib($1 - 1) + fib($1 - 2)
  END;
END;
$$ LANGUAGE plpgsql;

WITH RECURSIVE wholeNumbers(n) AS (
    VALUES (0)
  UNION ALL
    SELECT n+1 FROM wholeNumbers
)
SELECT fib(n) FROM wholeNumbers LIMIT 10;
